/** Node.js build plugin. Produces a server for workflow runs and agent interactions. */
import {
	agentVarName,
	channelVarName,
	generateBuiltModuleNormalizationSource,
	workflowVarName,
} from './generated-entry-normalization.ts';
import type { BuildContext, BuildPlugin } from './types.ts';

export class NodePlugin implements BuildPlugin {
	name = 'node';
	bundle: BuildPlugin['bundle'] = 'vite';

	generateEntryPoint(ctx: BuildContext): string {
		const { agents, appEntry, channels, dbEntry, workflows } = ctx;
		const runtimeVersion = JSON.stringify(ctx.runtimeVersion);

		const agentImports = agents
			.map((a, index) => {
				const varName = agentVarName(a.name, index);
				return `import * as ${varName} from ${JSON.stringify(a.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');

		const workflowImports = workflows
			.map((workflow, index) => {
				const varName = workflowVarName(workflow.name, index);
				return `import * as ${varName} from ${JSON.stringify(workflow.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');
		const channelImports = channels
			.map((channel, index) => {
				const varName = channelVarName(channel.name, index);
				return `import * as ${varName} from ${JSON.stringify(channel.filePath.replace(/\\/g, '/'))};`;
			})
			.join('\n');

		const agentModuleEntries = agents
			.map((a, index) => `  ${JSON.stringify(a.name)}: ${agentVarName(a.name, index)},`)
			.join('\n');
		const workflowModuleEntries = workflows
			.map(
				(workflow, index) =>
					`  ${JSON.stringify(workflow.name)}: ${workflowVarName(workflow.name, index)},`,
			)
			.join('\n');
		const channelModuleEntries = channels
			.map(
				(channel, index) =>
					`  ${JSON.stringify(channel.name)}: ${channelVarName(channel.name, index)},`,
			)
			.join('\n');

		// User-supplied app.ts (if any). The generated entry imports the user's
		// default export and dispatches all requests through `app.fetch`. When
		// no app.ts is present, the generated entry constructs a thin default
		// Hono that mounts `flue()` and renders canonical error envelopes.
		const userAppImport = appEntry
			? `import userApp from ${JSON.stringify(appEntry.replace(/\\/g, '/'))};`
			: '';
		const userDbImport = dbEntry
			? `import userPersistenceAdapter from ${JSON.stringify(dbEntry.replace(/\\/g, '/'))};`
			: '';

		// All HTTP routing, workflow admission, agent dispatch, and error
		// rendering live in @flue/runtime's runtime modules. The generated
		// entry's job is narrow: import handlers, build the runtime config,
		// instantiate sandboxes, start the listener.
		const builtModuleNormalizationSource = generateBuiltModuleNormalizationSource();
		return `
// Auto-generated by flue (target: node)
import { serve } from '@hono/node-server';
import { sqlite } from '@flue/runtime/node';
import createDebug from 'debug';
import {
  Bash,
  InMemoryFs,
  admitDetachedWorkflow,
  assertWorkflowDefinition,
  createFlueContext,
  createNodeAgentCoordinator,
  createNodeDispatchQueue,
  bashFactoryToSessionEnv,
  resolveModel,
  configureFlueRuntime,
  createDefaultFlueApp,
  invokeWorkflowAttached,
  invokeDirectAttached,
  generateWorkflowRunId,
  installDevLifecycleLogger,
} from '@flue/runtime/internal';
${agentImports}
${workflowImports}
${channelImports}
${userAppImport}
${userDbImport}

// ─── Config ─────────────────────────────────────────────────────────────────

const debugStartup = createDebug('flue:server:startup');

${builtModuleNormalizationSource}
const agentModules = {
${agentModuleEntries}
};
const workflowModules = {
${workflowModuleEntries}
};
const channelModules = {
${channelModuleEntries}
};
const normalized = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const { agents, workflows, channelHandlers } = normalized;

const isLocalMode = process.env.FLUE_MODE === 'local';
const devLifecycle = isLocalMode && process.env.FLUE_INTERNAL_DEV_LOGS === '1' ? installDevLifecycleLogger() : undefined;
const localCliTarget = process.env.FLUE_CLI_TARGET;
const localCliName = process.env.FLUE_CLI_NAME;
const localCliId = process.env.FLUE_CLI_ID;
// IPC mode requires the explicit internal gate set by the Flue CLI in
// addition to the target vars, so user-supplied FLUE_CLI_* values alone
// can never switch a production server into IPC mode.
const isLocalCliMode =
  process.env.FLUE_INTERNAL_CLI_IPC === '1' &&
  (localCliTarget !== undefined || localCliName !== undefined || localCliId !== undefined);
const hasIpcChannel = typeof process.send === 'function';
if (isLocalCliMode && !hasIpcChannel) {
  console.warn('[flue] FLUE_INTERNAL_CLI_IPC is set but no IPC channel was inherited; ignoring it and starting the HTTP server.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

${
	dbEntry
		? `// Custom persistence from db.ts. connect() is awaited once at startup so
// an unreachable or misconfigured database fails at boot, not inside the
// first request.
if (!userPersistenceAdapter || typeof userPersistenceAdapter.connect !== 'function') {
  throw new Error('[flue] db.ts must default-export a PersistenceAdapter with a connect() method.');
}
let executionStore;
let runStore;
let eventStreamStore;
try {
  if (userPersistenceAdapter.migrate) await userPersistenceAdapter.migrate();
  const stores = await userPersistenceAdapter.connect();
  if (!stores || typeof stores !== 'object') {
    throw new Error('connect() must return { executionStore, runStore, eventStreamStore }.');
  }
  ({ executionStore, runStore, eventStreamStore } = stores);
  if (!executionStore || typeof executionStore.sessions?.save !== 'function' || typeof executionStore.submissions?.getSubmission !== 'function') {
    throw new Error('connect() must return an executionStore with sessions and submissions.');
  }
  if (!runStore || typeof runStore.createRun !== 'function' || typeof runStore.listRuns !== 'function') {
    throw new Error('connect() must return a runStore.');
  }
  if (!eventStreamStore || typeof eventStreamStore.appendEvent !== 'function' || typeof eventStreamStore.readEvents !== 'function') {
    throw new Error('connect() must return an eventStreamStore.');
  }
} catch (error) {
  throw new Error('[flue] Failed to initialize persistence from db.ts: ' + (error instanceof Error ? error.message : error), { cause: error });
}`
		: `// Default persistence for Node — in-memory SQLite, process lifetime.
const defaultAdapter = sqlite();
if (defaultAdapter.migrate) await defaultAdapter.migrate();
const { executionStore, runStore, eventStreamStore } = await defaultAdapter.connect();`
}
const persistenceAdapter = ${dbEntry ? `userPersistenceAdapter` : `defaultAdapter`};
const agentCoordinator = createNodeAgentCoordinator({
  submissions: executionStore.submissions,
  sessions: executionStore.sessions,
  agents,
  createContext: createAgentContextForRequest,
  eventStreamStore,
  onInteractionStart: devLifecycle?.onAgentInteractionStart,
});
const dispatchQueue = createNodeDispatchQueue(agentCoordinator);

function createAgentContextForRequest({ id, request, initialEventIndex, dispatchId }) {
  return createFlueContext({
    id,
    dispatchId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

function createWorkflowContextForRequest({ runId, request, initialEventIndex }) {
  return createFlueContext({
    id: runId,
    runId,
    initialEventIndex,
    env: process.env,
    req: request,
    agentConfig: { resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

// ─── Runtime seed ───────────────────────────────────────────────────────────

// Seed the public flue() sub-app with everything it needs to dispatch agent
// requests in-process. Must run before \`flue()\` handles any request — by
// virtue of being a top-level statement, it executes before \`serve(...)\`
// below binds the listener. User app.ts files that call \`flue()\` at top
// level are also fine because Hono routes are lazy: they read this config
// only when a request arrives.
configureFlueRuntime({
  target: 'node',
  devMode: isLocalMode,
  runtimeVersion: ${runtimeVersion},
  agents,
  workflows,
  createAgentAdmission: (agentName, instanceId) =>
    agentCoordinator.createAdmission(agentName, instanceId),
  dispatchQueue,
  admitWorkflow: ({ workflowName, input }) => {
    const workflow = workflows.find((record) => record.name === workflowName)?.definition;
    if (!workflow) throw new Error('[flue] Internal workflow admission target is not registered.');
    return admitDetachedWorkflow({
      workflowName,
      workflow,
      input,
      request: new Request('https://flue.invalid/_internal/workflows/' + encodeURIComponent(workflowName), { method: 'POST' }),
      createContext: createWorkflowContextForRequest,
      runStore,
      eventStreamStore,
    });
  },
  channelHandlers,
  createWorkflowContext: createWorkflowContextForRequest,
  runStore,
  eventStreamStore,
});

// Reconcile any interrupted submissions from a previous process.
// This is best-effort on startup — errors are logged but do not block the server.
agentCoordinator.reconcileSubmissions().catch((error) => {
  console.error('[flue] Startup submission reconciliation failed:', error);
});

// ─── App composition ────────────────────────────────────────────────────────

${
	appEntry
		? `// User-supplied app.ts: their default export owns the entire request
// pipeline. We just verify it exposes a fetch method and pass the
// listener through. flue() is available for them to mount, but the
// composition is theirs to author.
const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request) method.'
  );
}`
		: `// No app.ts: build the default app via @flue/runtime so the generated entry
// stays \`hono\`-free (users only need hono in their node_modules when
// they author their own app.ts). The default mounts \`flue()\` at root
// and renders canonical Flue envelopes for unmatched paths.
const flueApp = createDefaultFlueApp();`
}

// ─── Start ──────────────────────────────────────────────────────────────────

function sendLocalMessage(message, done) {
  if (!process.send) throw new Error('[flue] Local CLI execution requires an inherited IPC connection.');
  process.send(message, done);
}

function localRequest() {
  return new Request('https://flue.invalid/_cli', { method: 'POST' });
}

function localErrorMessage(reason, requestId) {
  return { type: 'error', requestId, error: { type: 'invalid_request', message: reason, details: reason } };
}

function failLocalStartup(reason) {
  sendLocalMessage(localErrorMessage(reason), () => process.exit(1));
}

function parseIpcWorkflowMessage(raw) {
  if (!raw || typeof raw !== 'object' || raw.type !== 'invoke' || typeof raw.requestId !== 'string') {
    throw new Error('IPC workflow messages must have type "invoke" and a string requestId.');
  }
  return { type: 'invoke', requestId: raw.requestId, input: raw.input };
}

function parseIpcAgentMessage(raw) {
  if (!raw || typeof raw !== 'object' || typeof raw.requestId !== 'string') {
    throw new Error('IPC agent messages must have a string requestId.');
  }
  if (raw.type !== 'prompt' || typeof raw.message !== 'string') {
    throw new Error('IPC agent messages must have type "prompt" with a string message.');
  }
  return { type: 'prompt', requestId: raw.requestId, message: raw.message };
}

function ipcErrorMessage(error, requestId, runId) {
  const publicError = error instanceof Error
    ? { type: 'internal_error', message: error.message, details: error.message }
    : { type: 'internal_error', message: String(error), details: String(error) };
  return runId === undefined
    ? { type: 'error', requestId, error: publicError }
    : { type: 'error', requestId, runId, error: publicError };
}

function startLocalWorkflow(name) {
  const workflow = workflows.find((record) => record.name === name)?.definition;
  if (!workflow) {
    failLocalStartup('Unknown workflow: ' + name);
    return;
  }
  let invoked = false;
  sendLocalMessage({ type: 'ready', target: 'workflow', name });
  process.on('message', (raw) => {
    let message;
    try {
      message = parseIpcWorkflowMessage(raw);
      if (invoked) {
        sendLocalMessage(localErrorMessage('Local workflow execution accepts one invocation only.', message.requestId));
        return;
      }
      invoked = true;
    } catch (error) {
      sendLocalMessage(ipcErrorMessage(error));
      return;
    }
    const runId = generateWorkflowRunId();
    sendLocalMessage({ type: 'started', requestId: message.requestId, runId });
    void invokeWorkflowAttached({
      workflowName: name,
      runId,
      input: message.input,
      request: localRequest(),
      workflow,
      createContext: createWorkflowContextForRequest,
      onEvent: (event) => sendLocalMessage({ type: 'event', requestId: message.requestId, runId, event }),
      runStore,
      eventStreamStore,
    }).then(
      (invocation) => sendLocalMessage({ type: 'result', requestId: message.requestId, runId, result: invocation.result ?? null }, () => process.exit(0)),
      (error) => sendLocalMessage(ipcErrorMessage(error, message.requestId, runId), () => process.exit(1)),
    );
  });
}

function startLocalAgent(name, id) {
  if (!id) {
    failLocalStartup('Local agent connection requires an instance id.');
    return;
  }
  if (!agents.some((agent) => agent.name === name)) {
    failLocalStartup('Unknown agent for admission: ' + name);
    return;
  }
  sendLocalMessage({ type: 'ready', target: 'agent', name, instanceId: id });
  process.on('message', (raw) => {
    let message;
    try {
      message = parseIpcAgentMessage(raw);
    } catch (error) {
      sendLocalMessage(ipcErrorMessage(error));
      return;
    }
    let didStart = false;
    void invokeDirectAttached({
      payload: { message: message.message },
      admitAttachedSubmission: agentCoordinator.createAdmission(name, id),
      onEvent: (event) => {
        if (!didStart) {
          didStart = true;
          sendLocalMessage({ type: 'started', requestId: message.requestId });
        }
        sendLocalMessage({ type: 'event', requestId: message.requestId, event });
      },
    }).then(
      (result) => sendLocalMessage({ type: 'result', requestId: message.requestId, result: result ?? null }),
      (error) => sendLocalMessage(ipcErrorMessage(error, message.requestId)),
    );
  });
}

if (isLocalCliMode && hasIpcChannel) {
  if (!localCliName || (localCliTarget !== 'workflow' && localCliTarget !== 'agent')) {
    failLocalStartup('Invalid local CLI target configuration.');
  } else if (localCliTarget === 'workflow') {
    startLocalWorkflow(localCliName);
  } else {
    startLocalAgent(localCliName, localCliId);
  }
  process.on('disconnect', async () => {
    await agentCoordinator.shutdown();
    if (persistenceAdapter.close) await persistenceAdapter.close();
    process.exit(0);
  });
} else {
  const port = parseInt(process.env.PORT || '3000', 10);
  const server = serve({
    fetch: (request, env) => flueApp.fetch(request, env),
    port,
    serverOptions: { requestTimeout: 0 },
  }, () => {
    console.log('[flue] Server listening on http://localhost:' + port);
    if (isLocalMode) {
      process.send?.('flue:dev-ready');
      debugStartup('mode=local');
    }
    debugStartup('agents=%s', ${JSON.stringify(agents.map((a) => a.name).join(', '))});
  });
  let shuttingDown = false;
  async function stop(signal, exitCode) {
    if (shuttingDown) return;
    shuttingDown = true;
    // Backstop: force-exit if any shutdown step stalls past the coordinator's
    // own drain timeout. unref() so the timer never keeps the process alive.
    setTimeout(() => {
      console.error('[flue] Shutdown timed out, exiting.');
      process.exit(exitCode);
    }, 60_000).unref();
    // 1. Drain active submissions (abort at turn boundary, wait with timeout).
    await agentCoordinator.shutdown();
    // 2. Close persistence adapter.
    if (persistenceAdapter.close) await persistenceAdapter.close();
    // 3. Close HTTP server. Destroy open connections (long-poll and SSE
    // readers are held open indefinitely) so close() can settle.
    await new Promise((resolve) => {
      server.close(resolve);
      server.closeAllConnections();
    });
    process.exit(exitCode);
  }
  process.on('SIGINT', () => { void stop('SIGINT', 130); });
  process.on('SIGTERM', () => { void stop('SIGTERM', 143); });
}
`;
	}

	external = ['node-liblzma', '@mongodb-js/zstd'];
}
